export interface Upazila {
  id: string;
  name: string;
  bnName: string;
}

export interface District {
  id: string;
  name: string;
  bnName: string;
  upazilas: Upazila[];
}

export interface Division {
  id: string;
  name: string;
  bnName: string;
  districts: District[];
}

export const DIVISIONS: Division[] = [
  {
    id: '1', name: 'Dhaka', bnName: 'ঢাকা',
    districts: [
      { id: '1', name: 'Dhaka', bnName: 'ঢাকা', upazilas: [{id:'1',name:'Dhamrai',bnName:'ধামরাই'},{id:'2',name:'Savar',bnName:'সাভার'},{id:'3',name:'Dohar',bnName:'দোহার'},{id:'4',name:'Keraniganj',bnName:'কেরানীগঞ্জ'},{id:'5',name:'Nawabganj',bnName:'নবাবগঞ্জ'}] },
      { id: '2', name: 'Faridpur', bnName: 'ফরিদপুর', upazilas: [{id:'6',name:'Faridpur Sadar',bnName:'ফরিদপুর সদর'},{id:'7',name:'Boalmari',bnName:'বোয়ালমারী'},{id:'8',name:'Alfadanga',bnName:'আলফাডাঙ্গা'},{id:'9',name:'Madhukhali',bnName:'মধুখালী'},{id:'10',name:'Nagarkanda',bnName:'নগরকান্দা'},{id:'11',name:'Saltha',bnName:'সালথা'},{id:'12',name:'Bhanga',bnName:'ভাঙ্গা'},{id:'13',name:'Charbhadrasan',bnName:'চর ভদ্রাসন'},{id:'14',name:'Sadarpur',bnName:'সদরপুর'}] },
      { id: '3', name: 'Gazipur', bnName: 'গাজীপুর', upazilas: [{id:'15',name:'Gazipur Sadar',bnName:'গাজীপুর সদর'},{id:'16',name:'Kaliakair',bnName:'কালিয়াকৈর'},{id:'17',name:'Kaliganj',bnName:'কালীগঞ্জ'},{id:'18',name:'Kapasia',bnName:'কাপাসিয়া'},{id:'19',name:'Sreepur',bnName:'শ্রীপুর'}] },
      { id: '4', name: 'Gopalganj', bnName: 'গোপালগঞ্জ', upazilas: [{id:'20',name:'Gopalganj Sadar',bnName:'গোপালগঞ্জ সদর'},{id:'21',name:'Muksudpur',bnName:'মুকসুদpur'},{id:'22',name:'Kashiani',bnName:'কাশিয়ানী'},{id:'23',name:'Kotalipara',bnName:'কোটালীপাড়া'},{id:'24',name:'Tungipara',bnName:'টুঙ্গিপাড়া'}] },
      { id: '5', name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ', upazilas: [{id:'25',name:'Kishoreganj Sadar',bnName:'কিশোরগঞ্জ সদর'},{id:'26',name:'Austagram',bnName:'অষ্টগ্রাম'},{id:'27',name:'Itna',bnName:'ইটনা'},{id:'28',name:'Karimgonj',bnName:'করিমগঞ্জ'},{id:'29',name:'Katiadi',bnName:'কটিয়াদি'},{id:'30',name:'Kuliarchar',bnName:'কুলিয়ারচর'},{id:'31',name:'Tarail',bnName:'তাড়াইল'},{id:'32',name:'Nikli',bnName:'নিকলী'},{id:'33',name:'Pakundia',bnName:'পাকুন্দিয়া'},{id:'34',name:'Bajitpur',bnName:'বাজিতপুর'},{id:'35',name:'Mithamoin',bnName:'মিঠামইন'},{id:'36',name:'Hosainpur',bnName:'হোসেনপুর'},{id:'37',name:'Bhairab',bnName:'ভৈরব'}] },
      { id: '6', name: 'Madaripur', bnName: 'মাদারীপুর', upazilas: [{id:'38',name:'Madaripur Sadar',bnName:'মাদারীপুর সদর'},{id:'39',name:'Shibchar',bnName:'শিবচর'},{id:'40',name:'Rajoir',bnName:'রাজৈর'},{id:'41',name:'Kalkini',bnName:'কালকিনি'},{id:'42',name:'Dashar',bnName:'ডাসার'}] },
      { id: '7', name: 'Manikganj', bnName: 'মানিকগঞ্জ', upazilas: [{id:'43',name:'Manikganj Sadar',bnName:'মানিকগঞ্জ সদর'},{id:'44',name:'Shibaloy',bnName:'শিবালয়'},{id:'45',name:'Ghior',bnName:'ঘিওর'},{id:'46',name:'Daulatpur',bnName:'দৌলতপুর'},{id:'47',name:'Saturia',bnName:'সাটুরিয়া'},{id:'48',name:'Singair',bnName:'সিংগাইর'},{id:'49',name:'Harirampur',bnName:'হরিরামপুর'}] },
      { id: '8', name: 'Munshiganj', bnName: 'মুন্সীগঞ্জ', upazilas: [{id:'50',name:'Munshiganj Sadar',bnName:'মুন্সীগঞ্জ সদর'},{id:'51',name:'Sreenagar',bnName:'শ্রীনগর'},{id:'52',name:'Lohajong',bnName:'লৌহজং'},{id:'53',name:'Sirajdikhan',bnName:'সিরাজদিখান'},{id:'54',name:'Tongibari',bnName:'টঙ্গিবাড়ী'},{id:'55',name:'Gazaria',bnName:'গজারিয়া'}] },
      { id: '9', name: 'Narayanganj', bnName: 'নারায়ণগঞ্জ', upazilas: [{id:'56',name:'Narayanganj Sadar',bnName:'নারায়ণগঞ্জ সদর'},{id:'57',name:'Bandar',bnName:'বন্দর'},{id:'58',name:'Sonargaon',bnName:'সোনারগাঁও'},{id:'59',name:'Araihazar',bnName:'আড়াইহাজার'},{id:'60',name:'Rupganj',bnName:'রূপগঞ্জ'}] },
      { id: '10', name: 'Narsingdi', bnName: 'নরসিংদী', upazilas: [{id:'61',name:'Narsingdi Sadar',bnName:'নরসিংদী সদর'},{id:'62',name:'Belabo',bnName:'বেলাবো'},{id:'63',name:'Monohardi',bnName:'মনোহরদী'},{id:'64',name:'Shibpur',bnName:'শিবপুর'},{id:'65',name:'Raipura',bnName:'রায়পুরা'},{id:'66',name:'Palash',bnName:'পলাশ'}] },
      { id: '11', name: 'Rajbari', bnName: 'রাজবাড়ী', upazilas: [{id:'67',name:'Rajbari Sadar',bnName:'রাজবাড়ী সদর'},{id:'68',name:'Goalanda',bnName:'গোয়ালন্দ'},{id:'69',name:'Pangsha',bnName:'পাংশা'},{id:'70',name:'Baliakandi',bnName:'বালিয়াকান্দি'},{id:'71',name:'Kalukhali',bnName:'কালুখালী'}] },
      { id: '12', name: 'Shariatpur', bnName: 'শরীয়তপুর', upazilas: [{id:'72',name:'Shariatpur Sadar',bnName:'শরীয়তপুর সদর'},{id:'73',name:'Zajira',bnName:'জাজিরা'},{id:'74',name:'Naria',bnName:'নড়িয়া'},{id:'75',name:'Bhedarganj',bnName:'ভেদরগঞ্জ'},{id:'76',name:'Damudya',bnName:'ডামুড্যা'},{id:'77',name:'Gosairhat',bnName:'গোসাইরহাট'}] },
      { id: '13', name: 'Tangail', bnName: 'টাঙ্গাইল', upazilas: [{id:'78',name:'Tangail Sadar',bnName:'টাঙ্গাইল সদর'},{id:'79',name:'Kalihati',bnName:'কালিহাতি'},{id:'80',name:'Ghatail',bnName:'ঘাটাইল'},{id:'81',name:'Basail',bnName:'বাসাইল'},{id:'82',name:'Gopalpur',bnName:'গোপালপুর'},{id:'83',name:'Mirzapur',bnName:'মির্জাপুর'},{id:'84',name:'Bhuapur',bnName:'ভূঞাপুর'},{id:'85',name:'Nagarpur',bnName:'নাগরপুর'},{id:'86',name:'Madhupur',bnName:'মধুপুর'},{id:'87',name:'Sakhipur',bnName:'সখিপুর'},{id:'88',name:'Delduar',bnName:'দেলদুয়ার'},{id:'89',name:'Dhanbari',bnName:'ধনবাড়ী'}] }
    ]
  },
  {
    id: '2', name: 'Chattogram', bnName: 'চট্টগ্রাম',
    districts: [
      { id: '14', name: 'Chattogram', bnName: 'চট্টগ্রাম', upazilas: [{id:'90',name:'Anwara',bnName:'আনোয়ারা'},{id:'91',name:'Karnaphuli',bnName:'কর্ণফুলি'},{id:'92',name:'Chandanaish',bnName:'চন্দনাইশ'},{id:'93',name:'Patiya',bnName:'পটিয়া'},{id:'94',name:'Fatikchhari',bnName:'ফটিকছড়ি'},{id:'95',name:'Banshkhali',bnName:'বাঁশখালী'},{id:'96',name:'Boalkhali',bnName:'বোয়ালখালী'},{id:'97',name:'Mirsharai',bnName:'মীরসরাই'},{id:'98',name:'Raozan',bnName:'রাউজান'},{id:'99',name:'Rangunia',bnName:'রাঙ্গুনিয়া'},{id:'100',name:'Lohagara',bnName:'লোহাগাড়া'},{id:'101',name:'Sandwip',bnName:'সন্দ্বীপ'},{id:'102',name:'Satkania',bnName:'সাতকানিয়া'},{id:'103',name:'Sitakunda',bnName:'সীতাকুন্ড'},{id:'104',name:'Hathazari',bnName:'হাটহাজারী'}] },
      { id: '15', name: 'Cox\'s Bazar', bnName: 'কক্সবাজার', upazilas: [{id:'105',name:'Ukhia',bnName:'উখিয়া'},{id:'106',name:'Cox\'s Bazar Sadar',bnName:'কক্সবাজার সদর'},{id:'107',name:'Kutubdia',bnName:'কুতুবদিয়া'},{id:'108',name:'Chakaria',bnName:'চকরিয়া'},{id:'109',name:'Teknaf',bnName:'টেকনাফ'},{id:'110',name:'Pekua',bnName:'পেকুয়া'},{id:'111',name:'Maheshkhali',bnName:'মহেশখালী'},{id:'112',name:'Ramu',bnName:'রামু'},{id:'113',name:'Eidgaon',bnName:'ঈদগাঁও'}] },
      { id: '16', name: 'Bandarban', bnName: 'বান্দরবান', upazilas: [{id:'114',name:'Alikadam',bnName:'আলীকদম'},{id:'115',name:'Thanchi',bnName:'থানচি'},{id:'116',name:'Naikhongchhari',bnName:'নাইক্ষ্যংছড়ি'},{id:'117',name:'Bandarban Sadar',bnName:'বান্দরবান সদর'},{id:'118',name:'Ruma',bnName:'রুমা'},{id:'119',name:'Rowangchhari',bnName:'রোয়াংছড়ি'},{id:'120',name:'Lama',bnName:'লামা'}] },
      { id: '17', name: 'Khagrachhari', bnName: 'খাগড়াছড়ি', upazilas: [{id:'121',name:'Khagrachhari Sadar',bnName:'খাগড়াছড়ি সদর'},{id:'122',name:'Dighinala',bnName:'দীঘিনালা'},{id:'123',name:'Panchhari',bnName:'পানছড়ি'},{id:'124',name:'Mahalchhari',bnName:'মহালছড়ি'},{id:'125',name:'Matiranga',bnName:'মাটিরাঙ্গা'},{id:'126',name:'Manikchhari',bnName:'মানিকছড়ি'},{id:'127',name:'Ramgarh',bnName:'রামগড়'},{id:'128',name:'Lakshmichhari',bnName:'লক্ষ্মীছড়ি'},{id:'129',name:'Guimara',bnName:'গুইমারা'}] },
      { id: '18', name: 'Rangamati', bnName: 'রাঙ্গামাটি', upazilas: [{id:'130',name:'Kawkhali',bnName:'কাউখালী'},{id:'131',name:'Kaptai',bnName:'কাপ্তাই'},{id:'132',name:'Juraichhari',bnName:'জুরাছড়ি'},{id:'133',name:'Naniarchar',bnName:'নানিয়ারচর'},{id:'134',name:'Barkal',bnName:'বরকল'},{id:'135',name:'Baghaichhari',bnName:'বাঘাইছড়ি'},{id:'136',name:'Belaichhari',bnName:'বিলাইছড়ি'},{id:'137',name:'Rangamati Sadar',bnName:'রাঙ্গামাটি সদর'},{id:'138',name:'Rajasthali',bnName:'রাজস্থলী'},{id:'139',name:'Langadu',bnName:'লংগদু'}] },
      { id: '19', name: 'Noakhali', bnName: 'নোয়াখালী', upazilas: [{id:'140',name:'Noakhali Sadar',bnName:'নোয়াখালী সদর'},{id:'141',name:'Begumganj',bnName:'বেগমগঞ্জ'},{id:'142',name:'Chatkhil',bnName:'চাটখিল'},{id:'143',name:'Senbagh',bnName:'সেনবাগ'},{id:'144',name:'Hatiya',bnName:'হাতিয়া'},{id:'145',name:'Companiganj',bnName:'কোম্পানীগঞ্জ'},{id:'146',name:'Subarnachar',bnName:'সুবর্ণ চর'},{id:'147',name:'Sonaimuri',bnName:'সোনাইমুড়ি'},{id:'148',name:'Kabirhat',bnName:'কবিরহাট'}] },
      { id: '20', name: 'Lakshmipur', bnName: 'লক্ষ্মীপুর', upazilas: [{id:'149',name:'Kamalnagar',bnName:'কমলনগর'},{id:'150',name:'Ramganj',bnName:'রামগঞ্জ'},{id:'151',name:'Ramgati',bnName:'রামগতি'},{id:'152',name:'Raipur',bnName:'রায়পুর'},{id:'153',name:'Lakshmipur Sadar',bnName:'লক্ষ্মীপুর সদর'}] },
      { id: '21', name: 'Feni', bnName: 'ফেনী', upazilas: [{id:'154',name:'Feni Sadar',bnName:'ফেনী সদর'},{id:'155',name:'Daganbhuiyan',bnName:'দাগনভূঁইয়া'},{id:'156',name:'Sonagazi',bnName:'সোনাগাজী'},{id:'157',name:'Chhagalnaiya',bnName:'ছাগলনাইয়া'},{id:'158',name:'Parshuram',bnName:'পরশুরাম'},{id:'159',name:'Fulgazi',bnName:'ফুলগাজী'}] },
      { id: '22', name: 'Cumilla', bnName: 'কুমিল্লা', upazilas: [{id:'160',name:'Barura',bnName:'বরুড়া'},{id:'161',name:'Chandina',bnName:'চান্দিনা'},{id:'162',name:'Daudkandi',bnName:'দাউদকান্দি'},{id:'163',name:'Laksam',bnName:'লাকসাম'},{id:'164',name:'Brahmanpara',bnName:'ব্রাহ্মণপাড়া'},{id:'165',name:'Burichang',bnName:'বুড়িচং'},{id:'166',name:'Chauddagram',bnName:'চৌদ্দগ্রাম'},{id:'167',name:'Debidwar',bnName:'দেবিদ্বার'},{id:'168',name:'Homna',bnName:'হোমনা'},{id:'169',name:'Muradnagar',bnName:'মুরাদনগর'},{id:'170',name:'Nangalkot',bnName:'নাঙ্গলকোট'},{id:'171',name:'Meghna',bnName:'মেঘনা'},{id:'172',name:'Titas',bnName:'তিতাস'},{id:'173',name:'Monohargonj',bnName:'মনোহরগঞ্জ'},{id:'174',name:'Cumilla Adarsha Sadar',bnName:'কুমিল্লা আদর্শ সদর'},{id:'175',name:'Cumilla Sadar Dakshin',bnName:'কুমিল্লা সদর দক্ষিণ'},{id:'176',name:'Lalmai',bnName:'লালমাই'}] },
      { id: '23', name: 'Chandpur', bnName: 'চাঁদপুর', upazilas: [{id:'177',name:'Chandpur Sadar',bnName:'চাঁদপুর সদর'},{id:'178',name:'Hajiganj',bnName:'হাজীগঞ্জ'},{id:'179',name:'Kachua',bnName:'কচুয়া'},{id:'180',name:'Faridganj',bnName:'ফরিদগঞ্জ'},{id:'181',name:'Matlab Uttar',bnName:'মতলব উত্তর'},{id:'182',name:'Matlab Dakshin',bnName:'মতলব দক্ষিণ'},{id:'183',name:'Haimchar',bnName:'হাইমচর'},{id:'184',name:'Shahrasti',bnName:'শাহরাস্তি'}] },
      { id: '24', name: 'Brahmanbaria', bnName: 'ব্রাহ্মণবাড়িয়া', upazilas: [{id:'185',name:'Ashuganj',bnName:'আশুগঞ্জ'},{id:'186',name:'Akhaura',bnName:'আখাউড়া'},{id:'187',name:'Kasba',bnName:'কসবা'},{id:'188',name:'Nabinagar',bnName:'নবীনগর'},{id:'189',name:'Nasirnagar',bnName:'নাসিরনগর'},{id:'190',name:'Bancharampur',bnName:'বাঞ্ছারামপুর'},{id:'191',name:'Brahmanbaria Sadar',bnName:'ব্রাহ্মণবাড়িয়া সদর'},{id:'192',name:'Sarail',bnName:'সরাইল'},{id:'193',name:'Bijoynagar',bnName:'বিজয়নগর'}] }
    ]
  },
  {
    id: '3', name: 'Khulna', bnName: 'খুলনা',
    districts: [
      { id: '25', name: 'Kushtia', bnName: 'কুষ্টিয়া', upazilas: [{id:'194',name:'Kumarkhali',bnName:'কুমারখালী'},{id:'195',name:'Kushtia Sadar',bnName:'কুষ্টিয়া সদর'},{id:'196',name:'Khoksa',bnName:'খোকসা'},{id:'197',name:'Daulatpur',bnName:'দৌলতপুর'},{id:'198',name:'Bheramara',bnName:'ভেড়ামারা'},{id:'199',name:'Mirpur',bnName:'মিরপুর'}] },
      { id: '26', name: 'Khulna', bnName: 'খুলনা', upazilas: [{id:'200',name:'Koyra',bnName:'কয়রা'},{id:'201',name:'Dumuria',bnName:'ডুমুরিয়া'},{id:'202',name:'Terokhada',bnName:'তেরখাদা'},{id:'203',name:'Dacope',bnName:'দাকোপ'},{id:'204',name:'Dighalia',bnName:'দিঘলিয়া'},{id:'205',name:'Paikgachha',bnName:'পাইকগাছা'},{id:'206',name:'Phultala',bnName:'ফুলতলা'},{id:'207',name:'Batiaghata',bnName:'বটিয়াঘাটা'},{id:'208',name:'Rupsha',bnName:'রূপসা'}] },
      { id: '27', name: 'Chuadanga', bnName: 'চুয়াডাঙ্গা', upazilas: [{id:'209',name:'Alamdanga',bnName:'আলমডাঙ্গা'},{id:'210',name:'Chuadanga Sadar',bnName:'চুয়াডাঙ্গা সদর'},{id:'211',name:'Jibannagar',bnName:'জীবননগর'},{id:'212',name:'Damurhuda',bnName:'দামুড়হুদা'}] },
      { id: '28', name: 'Jhenaidah', bnName: 'ঝিনাইদহ', upazilas: [{id:'213',name:'Kaliganj',bnName:'কালীগঞ্জ'},{id:'214',name:'Kotchandpur',bnName:'কোটচাঁদপুর'},{id:'215',name:'Jhenaidah Sadar',bnName:'ঝিনাইদহ সদর'},{id:'216',name:'Maheshpur',bnName:'মহেশপুর'},{id:'217',name:'Shailkupa',bnName:'শৈলকুপা'},{id:'218',name:'Harinakundu',bnName:'হরিণাকুণ্ডু'}] },
      { id: '29', name: 'Narail', bnName: 'নড়াইল', upazilas: [{id:'219',name:'Kalia',bnName:'কালিয়া'},{id:'220',name:'Narail Sadar',bnName:'নড়াইল সদর'},{id:'221',name:'Lohagara',bnName:'লোহাগড়া'}] },
      { id: '30', name: 'Bagerhat', bnName: 'বাগেরহাট', upazilas: [{id:'222',name:'Kachua',bnName:'কচুয়া'},{id:'223',name:'Chitalmari',bnName:'চিতলমারী'},{id:'224',name:'Fakirhat',bnName:'ফকিরহাট'},{id:'225',name:'Bagerhat Sadar',bnName:'বাগেরহাট সদর'},{id:'226',name:'Mongla',bnName:'মোংলা'},{id:'227',name:'Morrelganj',bnName:'মোড়েলগঞ্জ'},{id:'228',name:'Mollahat',bnName:'মোল্লাহাট'},{id:'229',name:'Rampal',bnName:'রামপাল'},{id:'230',name:'Sharankhola',bnName:'শরণখোলা'}] },
      { id: '31', name: 'Magura', bnName: 'মাগুরা', upazilas: [{id:'231',name:'Magura Sadar',bnName:'মাগুরা সদর'},{id:'232',name:'Mohammadpur',bnName:'মোহাম্মদপুর'},{id:'233',name:'Shalikha',bnName:'শালিখা'},{id:'234',name:'Sreepur',bnName:'শ্রীপুর'}] },
      { id: '32', name: 'Meherpur', bnName: 'মেহেরপুর', upazilas: [{id:'235',name:'Gangni',bnName:'গাংনী'},{id:'236',name:'Meherpur Sadar',bnName:'মেহেরপুর সদর'},{id:'237',name:'Mujibnagar',bnName:'মুজিবনগর'}] },
      { id: '33', name: 'Jashore', bnName: 'যশোর', upazilas: [{id:'238',name:'Abhaynagar',bnName:'অভয়নগর'},{id:'239',name:'Keshabpur',bnName:'কেশবপুর'},{id:'240',name:'Chaugachha',bnName:'চৌগাছা'},{id:'241',name:'Jhikargachha',bnName:'ঝিকরগাছা'},{id:'242',name:'Bagherpara',bnName:'বাঘারপাড়া'},{id:'243',name:'Manirampur',bnName:'মণিরামপুর'},{id:'244',name:'Jashore Sadar',bnName:'যশোর সদর'},{id:'245',name:'Sharsha',bnName:'শার্শা'}] },
      { id: '34', name: 'Satkhira', bnName: 'সাতক্ষীরা', upazilas: [{id:'246',name:'Assasuni',bnName:'আশাশুনি'},{id:'247',name:'Kalaroa',bnName:'কলারোয়া'},{id:'248',name:'Kaliganj',bnName:'কালীগঞ্জ'},{id:'249',name:'Tala',bnName:'তালা'},{id:'250',name:'Debhata',bnName:'দেবহাটা'},{id:'251',name:'Shyamnagar',bnName:'শ্যামনগর'},{id:'252',name:'Satkhira Sadar',bnName:'সাতক্ষীরা সদর'}] }
    ]
  },
  {
    id: '4', name: 'Barishal', bnName: 'বরিশাল',
    districts: [
      { id: '35', name: 'Barishal', bnName: 'বরিশাল', upazilas: [{id:'253',name:'Agailjhara',bnName:'আগৈলঝারা'},{id:'254',name:'Bakerganj',bnName:'বাকেরগঞ্জ'},{id:'255',name:'Babuganj',bnName:'বাবুগঞ্জ'},{id:'256',name:'Banaripara',bnName:'বানারীপাড়া'},{id:'257',name:'Gournadi',bnName:'গৌরনদী'},{id:'258',name:'Hizla',bnName:'হিজলা'},{id:'259',name:'Barishal Sadar',bnName:'বরিশাল সদর'},{id:'260',name:'Mehendiganj',bnName:'মেহেন্দীগঞ্জ'},{id:'261',name:'Muladi',bnName:'মুলাদী'},{id:'262',name:'Wazirpur',bnName:'উজিরপুর'}] },
      { id: '36', name: 'Barguna', bnName: 'বরগুনা', upazilas: [{id:'263',name:'Barguna Sadar',bnName:'বরগুনা সদর'},{id:'264',name:'Amtali',bnName:'আমতলী'},{id:'265',name:'Taltali',bnName:'তালতলী'},{id:'266',name:'Patharghata',bnName:'পাথরঘাটা'},{id:'267',name:'Betagi',bnName:'বেতাগী'},{id:'268',name:'Bamna',bnName:'বামনা'}] },
      { id: '37', name: 'Bhola', bnName: 'ভোলা', upazilas: [{id:'269',name:'Char Fasson',bnName:'চরফ্যাসন'},{id:'270',name:'Tazumuddin',bnName:'তজুমদ্দিন'},{id:'271',name:'Daulatkhan',bnName:'দৌলতখান'},{id:'272',name:'Burhanuddin',bnName:'বোরহানউদ্দিন'},{id:'273',name:'Bhola Sadar',bnName:'ভোলা সদর'},{id:'274',name:'Manpura',bnName:'মনপুরা'},{id:'275',name:'Lalmohan',bnName:'লালমোহন'}] },
      { id: '38', name: 'Jhalokati', bnName: 'ঝালকাঠি', upazilas: [{id:'276',name:'Kathalia',bnName:'কাঁঠালিয়া'},{id:'277',name:'Jhalokati Sadar',bnName:'ঝালকাঠি সদর'},{id:'278',name:'Nalchity',bnName:'নলছিটি'},{id:'279',name:'Rajapur',bnName:'রাজাপুর'}] },
      { id: '39', name: 'Patuakhali', bnName: 'পটুয়াখালী', upazilas: [{id:'280',name:'Patuakhali Sadar',bnName:'পটুয়াখালী সদর'},{id:'281',name:'Bauphal',bnName:'বাউফল'},{id:'282',name:'Dashmina',bnName:'দশমিনা'},{id:'283',name:'Galachipa',bnName:'গলাচিপা'},{id:'284',name:'Kalapara',bnName:'কলাপাড়া'},{id:'285',name:'Mirzaganj',bnName:'মির্জাগঞ্জ'},{id:'286',name:'Dumki',bnName:'দুমকি'},{id:'287',name:'Rangabali',bnName:'রাঙ্গাবালী'}] },
      { id: '40', name: 'Pirojpur', bnName: 'পিরোজপুর', upazilas: [{id:'288',name:'Kawkhali',bnName:'কাউখালী'},{id:'289',name:'Nazirpur',bnName:'নাজিরপুর'},{id:'290',name:'Nesarabad',bnName:'নেছারাবাদ (স্বরূপকাঠি)'},{id:'291',name:'Pirojpur Sadar',bnName:'পিরোজপুর সদর'},{id:'292',name:'Bhandaria',bnName:'ভাণ্ডারিয়া'},{id:'293',name:'Mathbaria',bnName:'মঠবাড়িয়া'},{id:'294',name:'Indurkani',bnName:'ইন্দুরকানী'}] }
    ]
  },
  {
    id: '5', name: 'Mymensingh', bnName: 'ময়মনসিংহ',
    districts: [
      { id: '41', name: 'Mymensingh', bnName: 'ময়মনসিংহ', upazilas: [{id:'295',name:'Mymensingh Sadar',bnName:'ময়মনসিংহ সদর'},{id:'296',name:'Trishal',bnName:'ত্রিশাল'},{id:'297',name:'Gauripur',bnName:'গৌরীপুর'},{id:'298',name:'Muktagachha',bnName:'মুক্তাগাছা'},{id:'299',name:'Phulpur',bnName:'ফুলপুর'},{id:'300',name:'Tarakanda',bnName:'তারাকান্দা'},{id:'301',name:'Haluaghat',bnName:'হালুয়াঘাট'},{id:'302',name:'Bhaluka',bnName:'ভালুকা'},{id:'303',name:'Fulbaria',bnName:'ফুলবাড়ীয়া'},{id:'304',name:'Gaffargaon',bnName:'গফরগাঁও'},{id:'305',name:'Ishwarganj',bnName:'ঈশ্বরগঞ্জ'},{id:'306',name:'Nandail',bnName:'নান্দাইল'},{id:'307',name:'Dhobaura',bnName:'ধোবাউড়া'}] },
      { id: '42', name: 'Sherpur', bnName: 'শেরপুর', upazilas: [{id:'308',name:'Jhenaigati',bnName:'ঝিনাইগাতী'},{id:'309',name:'Nakla',bnName:'নকলা'},{id:'310',name:'Nalitabari',bnName:'নালিতাবাড়ী'},{id:'311',name:'Sherpur Sadar',bnName:'শেরপুর সদর'},{id:'312',name:'Sreebardi',bnName:'শ্রীবরদী'}] },
      { id: '43', name: 'Jamalpur', bnName: 'জামালপুর', upazilas: [{id:'313',name:'Jamalpur Sadar',bnName:'জামালপুর সদর'},{id:'314',name:'Bakshiganj',bnName:'বকশীগঞ্জ'},{id:'315',name:'Dewanganj',bnName:'দেওয়ানগঞ্জ'},{id:'316',name:'Islampur',bnName:'ইসলামপুর'},{id:'317',name:'Madarganj',bnName:'মাদারগঞ্জ'},{id:'318',name:'Melandaha',bnName:'মেলান্দহ'},{id:'319',name:'Sarishabari',bnName:'সরিষাবাড়ী'}] },
      { id: '44', name: 'Netrokona', bnName: 'নেত্রকোণা', upazilas: [{id:'320',name:'Atpara',bnName:'আটপাড়া'},{id:'321',name:'Barhatta',bnName:'বারহাট্টা'},{id:'322',name:'Durgapur',bnName:'দুর্গাপুর'},{id:'323',name:'Khaliajuri',bnName:'খালিয়াজুড়ি'},{id:'324',name:'Kalmakanda',bnName:'কলমাকান্দা'},{id:'325',name:'Kendua',bnName:'কেন্দুয়া'},{id:'326',name:'Madan',bnName:'মদন'},{id:'327',name:'Mohanganj',bnName:'মোহনগঞ্জ'},{id:'328',name:'Netrokona Sadar',bnName:'নেত্রকোণা সদর'},{id:'329',name:'Purbadhala',bnName:'পূর্বধলা'}] }
    ]
  },
  {
    id: '6', name: 'Rangpur', bnName: 'রংপুর',
    districts: [
      { id: '45', name: 'Rangpur', bnName: 'রংপুর', upazilas: [{id:'330',name:'Rangpur Sadar',bnName:'রংপুর সদর'},{id:'331',name:'Badarganj',bnName:'বদরগঞ্জ'},{id:'332',name:'Gangachara',bnName:'গংগাচড়া'},{id:'333',name:'Kaunia',bnName:'কাউনিয়া'},{id:'334',name:'Mithapukur',bnName:'মিঠাপুকুর'},{id:'335',name:'Pirgachha',bnName:'পীরগাছা'},{id:'336',name:'Pirganj',bnName:'পীরগঞ্জ'},{id:'337',name:'Taraganj',bnName:'তারাগঞ্জ'}] },
      { id: '46', name: 'Dinajpur', bnName: 'দিনাজপুর', upazilas: [{id:'338',name:'Birampur',bnName:'বিরামপুর'},{id:'339',name:'Birganj',bnName:'বীরগঞ্জ'},{id:'340',name:'Bochaganj',bnName:'বোচাগঞ্জ'},{id:'341',name:'Fulbari',bnName:'ফুলবাড়ী'},{id:'342',name:'Chirirbandar',bnName:'চিরিরবন্দর'},{id:'343',name:'Ghoraghat',bnName:'ঘোড়াঘাট'},{id:'344',name:'Hakimpur',bnName:'হাকিমপুর'},{id:'345',name:'Kaharole',bnName:'কাহারোল'},{id:'346',name:'Khansama',bnName:'খানসামা'},{id:'347',name:'Dinajpur Sadar',bnName:'দিনাজপুর সদর'},{id:'348',name:'Nawabganj',bnName:'নবাবগঞ্জ'},{id:'349',name:'Parbatipur',bnName:'পার্বতীপুর'},{id:'350',name:'Biral',bnName:'বিরল'}] },
      { id: '47', name: 'Gaibandha', bnName: 'গাইবান্ধা', upazilas: [{id:'351',name:'Gaibandha Sadar',bnName:'গাইবান্ধা সদর'},{id:'352',name:'Fulchhari',bnName:'ফুলছড়ি'},{id:'353',name:'Gobindaganj',bnName:'গোবিন্দগঞ্জ'},{id:'354',name:'Palashbari',bnName:'পলাশবাড়ী'},{id:'355',name:'Sadullapur',bnName:'সাদুল্লাপুর'},{id:'356',name:'Saghata',bnName:'সাঘাটা'},{id:'357',name:'Sundarganj',bnName:'সুন্দরগঞ্জ'}] },
      { id: '48', name: 'Kurigram', bnName: 'কুড়িগ্রাম', upazilas: [{id:'358',name:'Ulipur',bnName:'উলিপুর'},{id:'359',name:'Kurigram Sadar',bnName:'কুড়িগ্রাম সদর'},{id:'360',name:'Char Rajibpur',bnName:'চর রাজিবপুর'},{id:'361',name:'Chilmari',bnName:'চিলমারী'},{id:'362',name:'Nageshwari',bnName:'নাগেশ্বরী'},{id:'363',name:'Fulbari',bnName:'ফুলবাড়ী'},{id:'364',name:'Bhurungamari',bnName:'ভুরুঙ্গামারী'},{id:'365',name:'Rajarhat',bnName:'রাজারহাট'},{id:'366',name:'Roumari',bnName:'রৌমারী'}] },
      { id: '49', name: 'Nilphamari', bnName: 'নীলফামারী', upazilas: [{id:'367',name:'Nilphamari Sadar',bnName:'নীলফামারী সদর'},{id:'368',name:'Domar',bnName:'ডোমার'},{id:'369',name:'Dimla',bnName:'ডিমলা'},{id:'370',name:'Jaldhaka',bnName:'জলঢাকা'},{id:'371',name:'Kishoreganj',bnName:'কিশোরগঞ্জ'},{id:'372',name:'Sayedpur',bnName:'সৈয়দপুর'}] },
      { id: '50', name: 'Panchagarh', bnName: 'পঞ্চগড়', upazilas: [{id:'373',name:'Debiganj',bnName:'দেবীগঞ্জ'},{id:'374',name:'Tetulia',bnName:'তেতুলিয়া'},{id:'375',name:'Panchagarh Sadar',bnName:'পঞ্চগড় সদর'},{id:'376',name:'Atwari',bnName:'আটোয়ারী'},{id:'377',name:'Boda',bnName:'বোদা'}] },
      { id: '51', name: 'Thakurgaon', bnName: 'ঠাকুরগাঁও', upazilas: [{id:'378',name:'Thakurgaon Sadar',bnName:'ঠাকুরগাঁও সদর'},{id:'379',name:'Pirganj',bnName:'পীরগঞ্জ'},{id:'380',name:'Baliadangi',bnName:'বালিয়াডাঙ্গী'},{id:'381',name:'Ranisankail',bnName:'রানীশংকৈল'},{id:'382',name:'Haripur',bnName:'হরিপুর'}] },
      { id: '52', name: 'Lalmonirhat', bnName: 'লালমনিরহাট', upazilas: [{id:'383',name:'Aditmari',bnName:'আদিতমারী'},{id:'384',name:'Kaliganj',bnName:'কালীগঞ্জ'},{id:'385',name:'Patgram',bnName:'পাটগ্রাম'},{id:'386',name:'Lalmonirhat Sadar',bnName:'লালমনিরহাট সদর'},{id:'387',name:'Hatibandha',bnName:'হাতীবান্ধা'}] }
    ]
  },
  {
    id: '7', name: 'Rajshahi', bnName: 'রাজশাহী',
    districts: [
      { id: '53', name: 'Rajshahi', bnName: 'রাজশাহী', upazilas: [{id:'388',name:'Bagha',bnName:'বাঘা'},{id:'389',name:'Puthia',bnName:'পুঠিয়া'},{id:'390',name:'Paba',bnName:'পবা'},{id:'391',name:'Bagmara',bnName:'বাগমারা'},{id:'392',name:'Tanore',bnName:'তানোর'},{id:'393',name:'Mohanpur',bnName:'মোহনপুর'},{id:'394',name:'Charghat',bnName:'চারঘাট'},{id:'395',name:'Godagari',bnName:'গোদাগাড়ী'},{id:'396',name:'Durgapur',bnName:'দুর্গাপুর'}] },
      { id: '54', name: 'Natore', bnName: 'নাটোর', upazilas: [{id:'397',name:'Natore Sadar',bnName:'নাটোর সদর'},{id:'398',name:'Bagatipara',bnName:'বাগাতিপাড়া'},{id:'399',name:'Baraigram',bnName:'বড়াইগ্রাম'},{id:'400',name:'Gurudaspur',bnName:'গুরুদাসপুর'},{id:'401',name:'Lalpur',bnName:'লালপুর'},{id:'402',name:'Singra',bnName:'সিংড়া'},{id:'403',name:'Naldanga',bnName:'নলডাঙ্গা'}] },
      { id: '55', name: 'Chapainawabganj', bnName: 'চাঁপাইনবাবগঞ্জ', upazilas: [{id:'404',name:'Chapainawabganj Sadar',bnName:'চাঁপাইনবাবগঞ্জ সদর'},{id:'405',name:'Gomastapur',bnName:'গোমস্তাপুর'},{id:'406',name:'Shibganj',bnName:'শিবগঞ্জ'},{id:'407',name:'Nachole',bnName:'নাচোল'},{id:'408',name:'Bholahat',bnName:'ভোলাহাট'}] },
      { id: '56', name: 'Joypurhat', bnName: 'জয়পুরহাট', upazilas: [{id:'409',name:'Panchbibi',bnName:'পাঁচবিবি'},{id:'410',name:'Kalai',bnName:'কালাই'},{id:'411',name:'Khetlal',bnName:'ক্ষেতলাল'},{id:'412',name:'Akkelpur',bnName:'আক্কেলপুর'},{id:'413',name:'Joypurhat Sadar',bnName:'জয়পুরহাট সদর'}] },
      { id: '57', name: 'Naogaon', bnName: 'নওগাঁ', upazilas: [{id:'414',name:'Patnitala',bnName:'পত্নীতলা'},{id:'415',name:'Dhamoirhat',bnName:'ধামুরহাট'},{id:'416',name:'Mahadebpur',bnName:'মহাদেবপুর'},{id:'417',name:'Porsha',bnName:'পোরশা'},{id:'418',name:'Sapahar',bnName:'সাপাহার'},{id:'419',name:'Badalgachhi',bnName:'বদলগাছী'},{id:'420',name:'Manda',bnName:'মান্দা'},{id:'421',name:'Niamatpur',bnName:'নিয়ামতপুর'},{id:'422',name:'Atrai',bnName:'আত্রাই'},{id:'423',name:'Raninagar',bnName:'রানীনগর'},{id:'424',name:'Naogaon Sadar',bnName:'নওগাঁ সদর'}] },
      { id: '58', name: 'Bogura', bnName: 'বগুড়া', upazilas: [{id:'425',name:'Adamdighi',bnName:'আদমদীঘি'},{id:'426',name:'Bogura Sadar',bnName:'বগুড়া সদর'},{id:'427',name:'Dhunat',bnName:'ধুনট'},{id:'428',name:'Dupchanchia',bnName:'দুপচাঁচিয়া'},{id:'429',name:'Gabtali',bnName:'গাবতলী'},{id:'430',name:'Kahaloo',bnName:'কাহালু'},{id:'431',name:'Nandigram',bnName:'নন্দীগ্রাম'},{id:'432',name:'Sariakandi',bnName:'সারিয়াকান্দি'},{id:'433',name:'Sherpur',bnName:'শেরপুর'},{id:'434',name:'Shibganj',bnName:'শিবগঞ্জ'},{id:'435',name:'Sonatola',bnName:'সোনাতলা'},{id:'436',name:'Shahjahanpur',bnName:'শাজাহানপুর'}] },
      { id: '59', name: 'Pabna', bnName: 'পাবনা', upazilas: [{id:'437',name:'Atgharia',bnName:'আটঘরিয়া'},{id:'438',name:'Ishwardi',bnName:'ঈশ্বরদী'},{id:'439',name:'Chatmohar',bnName:'চাটমোহর'},{id:'440',name:'Pabna Sadar',bnName:'পাবনা সদর'},{id:'441',name:'Faridpur',bnName:'ফরিদপুর'},{id:'442',name:'Bera',bnName:'বেড়া'},{id:'443',name:'Bhangura',bnName:'ভাঙ্গুরা'},{id:'444',name:'Santhia',bnName:'সাঁথিয়া'},{id:'445',name:'Sujanagar',bnName:'সুজানগর'}] },
      { id: '60', name: 'Sirajganj', bnName: 'সিরাজগঞ্জ', upazilas: [{id:'446',name:'Ullapara',bnName:'উল্লাপাড়া'},{id:'447',name:'Kazipur',bnName:'কাজীপুর'},{id:'448',name:'Kamarkhanda',bnName:'কামারখন্দ'},{id:'449',name:'Chauhali',bnName:'চৌহালি'},{id:'450',name:'Tarash',bnName:'তাড়াশ'},{id:'451',name:'Belkuchi',bnName:'বেলকুচি'},{id:'452',name:'Raiganj',bnName:'রায়গঞ্জ'},{id:'453',name:'Shahjadpur',bnName:'শাহজাদপুর'},{id:'454',name:'Sirajganj Sadar',bnName:'সিরাজগঞ্জ সদর'}] }
    ]
  },
  {
    id: '8', name: 'Sylhet', bnName: 'সিলেট',
    districts: [
      { id: '61', name: 'Sylhet', bnName: 'সিলেট', upazilas: [{id:'455',name:'Sylhet Sadar',bnName:'সিলেট সদর'},{id:'456',name:'Dakshin Surma',bnName:'দক্ষিণ সুরমা'},{id:'457',name:'Bishwanath',bnName:'বিশ্বনাথ'},{id:'458',name:'Osmaninagar',bnName:'ওসমানীনগর'},{id:'459',name:'Balaganj',bnName:'বালাগঞ্জ'},{id:'460',name:'Fenchuganj',bnName:'ফেঞ্চুগঞ্জ'},{id:'461',name:'Golapganj',bnName:'গোলাপগঞ্জ'},{id:'462',name:'Beanibazar',bnName:'বিয়ানীবাজার'},{id:'463',name:'Zakiganj',bnName:'জকিগঞ্জ'},{id:'464',name:'Kanaighat',bnName:'কানাইঘাট'},{id:'465',name:'Jaintiapur',bnName:'জৈন্তাপুর'},{id:'466',name:'Gowainghat',bnName:'গোয়াইনঘাট'},{id:'467',name:'Companiganj',bnName:'কোম্পানীগঞ্জ'}] },
      { id: '62', name: 'Sunamganj', bnName: 'সুনামগঞ্জ', upazilas: [{id:'468',name:'Sunamganj Sadar',bnName:'সুনামগঞ্জ সদর'},{id:'469',name:'Bishwamvapur',bnName:'বিশ্বম্ভরপুর'},{id:'470',name:'Tahirpur',bnName:'তাহিরপুর'},{id:'471',name:'Madhyanagar',bnName:'মধ্যনগর'},{id:'472',name:'Dharmapasha',bnName:'ধর্মপাশা'},{id:'473',name:'Jamalganj',bnName:'জামালগঞ্জ'},{id:'474',name:'Shantiganj',bnName:'শান্তিগঞ্জ'},{id:'475',name:'Dowarabazar',bnName:'দোয়ারাবাজার'},{id:'476',name:'Chhatak',bnName:'ছাতক'},{id:'477',name:'Jagannathpur',bnName:'জগন্নাথপুর'},{id:'478',name:'Derai',bnName:'দিরাই'},{id:'479',name:'Shalla',bnName:'শাল্লা'}] },
      { id: '63', name: 'Habiganj', bnName: 'হবিগঞ্জ', upazilas: [{id:'480',name:'Habiganj Sadar',bnName:'হবিগঞ্জ সদর'},{id:'481',name:'Nabiganj',bnName:'নবীগঞ্জ'},{id:'482',name:'Bahubal',bnName:'বাহুবল'},{id:'483',name:'Chunarughat',bnName:'চুনারুঘাট'},{id:'484',name:'Sayestaganj',bnName:'শায়েস্তাগঞ্জ'},{id:'485',name:'Madhabpur',bnName:'মাধবপুর'},{id:'486',name:'Lakhai',bnName:'লাখাই'},{id:'487',name:'Baniyachong',bnName:'বানিয়াচং'},{id:'488',name:'Ajmiriganj',bnName:'আজমিরীগঞ্জ'}] },
      { id: '64', name: 'Maulvibazar', bnName: 'মৌলভীবাজার', upazilas: [{id:'489',name:'Maulvibazar Sadar',bnName:'মৌলভীবাজার সদর'},{id:'490',name:'Rajnagar',bnName:'রাজনগর'},{id:'491',name:'Sreemangal',bnName:'শ্রীমঙ্গল'},{id:'492',name:'Kamalganj',bnName:'কমলগঞ্জ'},{id:'493',name:'Kulaura',bnName:'কুলাউড়া'},{id:'494',name:'Juri',bnName:'জুড়ী'},{id:'495',name:'Barlekha',bnName:'বড়লেখা'}] }
    ]
  }
];
